### PR TITLE
Section parser for articles

### PR DESCRIPTION
**Pull request by mbelmadani**

### CODE REVIEW

**Comment by tyarkoni** [comment]
Hey, cool! Feel free to re-open this if you want me to merge it and I'll take a look.

**Comment by mbelmadani** [comment]
Hi there,

I will surely re-open it soon. I've only just finished my initial
implementation so I was hoping to test it a bit more thoroughly before
submitting it for review.

Let me know if you have any questions, or if you want me to re-open the
pull request anyways.

Cheers

**Comment by tyarkoni** [comment]
No worries,  I'll just wait till you're ready. Thanks!

**Comment by tyarkoni** [comment]
Oh, and let me know if you have questions about anything (though it looks
like you have it pretty well figured out). I apologize for the poor (well,
really nonexistent) state of the documentation.

**Comment by mbelmadani** [comment]
Sounds good! I think I mostly just need to implement the feature for the
remaining publisher platforms/Sources, and also have the feature
configurable through the config file (I haven't looked at this part yet,
but I'm thinking of something similar to the way parse_article works.) And
of course, test it!

No need to apologize, the code, comments and examples were plenty to get me
started. Thank you for open sourcing your work!

Cheers,

**Pull request closed without merging**
